### ISSUE TITLE
Log all outgoing data?

### ISSUE THREAD

**Issue by Aquive** [squeezely/magento2-plugin#16]
Hi, I see this extension has an advanced debug option. I am looking for a method to capture all outgoing data. I need to check this to see if we are compliant with regulations. Is this possible with the debug options, or do I need to build it myself?

**Comment by aalwash** [comment]
Hi Aquive,

Do you want to capture all outgoing Magento data?

Or only the one that are ment for Squeezely API?

**Comment by Aquive** [comment]
Hi,

@aalwash at least everything which is ment for the Squeezely API. What do you mean by outgoing Magento data? Is the data which is collected also send to another location besides the Squeezely API?

**Comment by aalwash** [comment]
Hi @Aquive 

No, I didn't understand your question, I was assuming you're looking for a plugin that shows all outgoing data of magento itself

The debug mode will show you all data we post to the Squeezely API
Let me know if this answers your question

**Comment by Aquive** [comment]
Logs will suffice, I will check it out thanks!

**Comment by Aquive** [comment]
Hi @aalwash,

Thanks for the suggestion, I examined the logs and made me understand the extension better. I also examined the code to understand which data is sent to the Squeezly server.

I have another question; I want to exclude certain products to be sent to Squeezly. I want to filter those based on a custom attribute. What is the best place to do this? Could you help me figure that out? Or is it maybe possible to get in touch with you our one of your tech colleges by phone?

The options I have so far:

- Write a plugin for each event (InitiateCheckout, ViewCategory etc.) which process product data. Filter out the products I want to exclude. This seems like a cumbersome process since there are 11 events in total (I could find).
- Capture the sent data just before it is processed with a plugin on, for instance in `/vendor/squeezely/magento2-plugin/Controller/Events/Get.php`. Check data for product information and filter it. I don't know how uniform the data is which is processed. I haven't looked into that yet. It would be ideal if it is uniform, and I could just grab the key with `products`
- I am looking further for better options I can find....

Any suggestions?

**Comment by aalwash** [comment]
Hi @Aquive 

You can always contact our support team support@squeezely.tech regarding any question you have about our products (including the magento plugin)

Regarding your situation, I don't think we can provide a solution for this, other then the solutions you're suggesting. 
The only problem is, if you're going to modify the magento plugin, they will be erased after a plugin update.

It's not possible for you to move these products to another storeview and disable the syncing there?

**Comment by Aquive** [comment]
Thanks for the suggestions. I solved it by making plugins and preferences on several places.
