### ISSUE TITLE
RemoveFromCart event not triggered by minicart?

### ISSUE THREAD

**Issue by Aquive** [squeezely/magento2-plugin#18]
I don't know if this is intended or not, but it seems that deleting a product from the minicart does not trigger RemoveFromCart event. Is this intentional? Or is it just my system, maybe?

**Comment by aalwash** [comment]
Hi @Aquive ,

It should work, I just tested on our development environment with a minicart setup

Do you have a public url where we can test/see this issue?

**Comment by Aquive** [comment]
I thought it was not working, maybe I misjudged. I didn't look too much into it.
