### ISSUE TITLE
Incorrect parameters of account create afterExecute plugin 

### ISSUE THREAD

**Issue by mischabraam** [squeezely/magento2-plugin#21]
Hi,

The after plugin defined as `\Squeezely\Plugin\Plugin\CustomerCreate::afterExecute` has incorrect function parameters.
This function is declared as followed.

```
    public function afterExecute(
        CreatePost $subject,
        Redirect $result
    ) {
```

Which states that it expects a `Redirect` instance of the original function. But that is not the case. 
In the original function `\Magento\Customer\Controller\Account\CreatePost::execute` there is a line as followed.
```
$resultRedirect = $this->accountRedirect->getRedirect();
```
This calls `$resultRedirect = $this->accountRedirect->getRedirect();` which can return a `Redirect` instance, but also an instance of `Forward`. If that happens a fatal error occurs because your plugin expects a wrong type.

**Comment by aalwash** [comment]
Hi @mischabraam ,

Thanks for notifying us, we will look into it and keep you posted

**Comment by mischabraam** [comment]
I think the after plugin's second parameter should be `\Magento\Framework\Controller\AbstractResult`

**Comment by aalwash** [comment]
Yes, makes sense, both Redirect and Forward extended from Magento\Framework\Controller\AbstractResult

In a few moments I will push a new version to composer and Magento Marketplace

Thank you for reporting this issue
