### ISSUE TITLE
Incorrect array in Webapi breaks it

### ISSUE THREAD

**Issue by jorgb90** [squeezely/magento2-plugin#23]
At line 20 of vendor/squeezely/magento2-plugin/Api/Webapi/ManagementInterface.php

     * @return array

must be 

     * @return mixed[]

otherwise it breaks the API.

**Comment by aalwash** [comment]
Thanks @jorgb90 , our team is investigating it.

Will update you as soon as we have more information.

**Comment by mfutselaar** [comment]
Problem still persists. It only triggers when you use the API apparently (eg. when using Hyva templates)

The Magento dependency compiler uses this part of the docblock and tries to create a `array` import which doesn't work obviously.

Like @jorgb90 said, the simplest fix is to just return the right type, in this case it would be `* return string[]`

**Comment by aalwash** [comment]
Hi, in the new version (2.7.0) we fixed this issue, see PR
