### ISSUE TITLE
Update module om Magento Marketplace

### ISSUE THREAD

**Issue by erwinromkes** [squeezely/magento2-plugin#28]
At the moment the latest version of the Squeezely M2 module is 2.7.0, but on the Magento Marketplace the latest version is 2.5.1. What happen when I want to install the 2.7.0 version for Magento 2.4.4 I get the following error:
> Higher matching version 2.7.0 of squeezely/magento2-plugin was found in public repository [packagist.org](http://packagist.org/) than 2.5.1 in private https://repo.magento.com/. Public package might've been taken over by a malicious entity, please investigate and update package requirement to match the version from the private repository.

Looks likes the fix is to update the module on marketplace 👍🏼

**Comment by Marvin-Magmodules** [comment]
Hi @erwinromkes, thank you for opening this issue! There were some issues with submitting packages to the Marketplace, but these have been resolved. The latest version v2.8.0 is now also available on the Marketplace; https://marketplace.magento.com/squeezely-magento2-plugin.html

We are closing this issue now but please feel free to reopen if you still encounter any issues.
